/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImagePut : ImagePut represents the modifiable fields of an image
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagePut {
    /// Whether the image should auto-update when a new build is available
    #[serde(rename = "auto_update", skip_serializing_if = "Option::is_none")]
    pub auto_update: Option<bool>,
    /// When the image becomes obsolete
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// List of profiles to use when creating from this image (if none provided by user)
    #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
    pub profiles: Option<Vec<String>>,
    /// Descriptive properties
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    /// Whether the image is available to unauthenticated users
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
}

impl ImagePut {
    /// ImagePut represents the modifiable fields of an image
    pub fn new() -> ImagePut {
        ImagePut {
            auto_update: None,
            expires_at: None,
            profiles: None,
            properties: None,
            public: None,
        }
    }
}

