/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageMetadata : ImageMetadata represents image metadata (used in image tarball)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageMetadata {
    /// Architecture name
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// Image creation data (as UNIX epoch)
    #[serde(rename = "creation_date", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<i64>,
    /// Image expiry data (as UNIX epoch)
    #[serde(rename = "expiry_date", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<i64>,
    /// Descriptive properties
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    /// Template for files in the image
    #[serde(rename = "templates", skip_serializing_if = "Option::is_none")]
    pub templates: Option<std::collections::HashMap<String, models::ImageMetadataTemplate>>,
}

impl ImageMetadata {
    /// ImageMetadata represents image metadata (used in image tarball)
    pub fn new() -> ImageMetadata {
        ImageMetadata {
            architecture: None,
            creation_date: None,
            expiry_date: None,
            properties: None,
            templates: None,
        }
    }
}

