/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageSource : ImageSource represents the source of an image
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageSource {
    /// Source alias to download from
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<String>,
    /// Source server certificate (if not trusted by system CA)
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    /// Type of image (container or virtual-machine)
    #[serde(rename = "image_type", skip_serializing_if = "Option::is_none")]
    pub image_type: Option<String>,
    /// Source server protocol
    #[serde(rename = "protocol", skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    /// URL of the source server
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
}

impl ImageSource {
    /// ImageSource represents the source of an image
    pub fn new() -> ImageSource {
        ImageSource {
            alias: None,
            certificate: None,
            image_type: None,
            protocol: None,
            server: None,
        }
    }
}

