/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageAlias : ImageAlias represents an alias from the alias list of an image
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageAlias {
    /// Description of the alias
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Name of the alias
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ImageAlias {
    /// ImageAlias represents an alias from the alias list of an image
    pub fn new() -> ImageAlias {
        ImageAlias {
            description: None,
            name: None,
        }
    }
}

