/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceFull {
    /// Architecture name
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// List of backups.
    #[serde(rename = "backups", skip_serializing_if = "Option::is_none")]
    pub backups: Option<Vec<models::InstanceBackup>>,
    /// Instance configuration (see doc/instances.md)
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// Instance creation timestamp
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Instance description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Instance devices (see doc/instances.md)
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<serde_json::Value>,
    /// Whether only the instances disk should be restored
    #[serde(rename = "disk_only", skip_serializing_if = "Option::is_none")]
    pub disk_only: Option<bool>,
    /// Whether the instance is ephemeral (deleted on shutdown)
    #[serde(rename = "ephemeral", skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    /// Expanded configuration (all profiles and local config merged)
    #[serde(rename = "expanded_config", skip_serializing_if = "Option::is_none")]
    pub expanded_config: Option<serde_json::Value>,
    /// Expanded devices (all profiles and local devices merged)
    #[serde(rename = "expanded_devices", skip_serializing_if = "Option::is_none")]
    pub expanded_devices: Option<serde_json::Value>,
    /// Last start timestamp
    #[serde(rename = "last_used_at", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// What cluster member this instance is located on
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Instance name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List of profiles applied to the instance
    #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
    pub profiles: Option<Vec<String>>,
    /// Instance project name
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<String>,
    /// If set, instance will be restored to the provided snapshot name
    #[serde(rename = "restore", skip_serializing_if = "Option::is_none")]
    pub restore: Option<String>,
    /// List of snapshots.
    #[serde(rename = "snapshots", skip_serializing_if = "Option::is_none")]
    pub snapshots: Option<Vec<models::InstanceSnapshot>>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<Box<models::InstanceState>>,
    /// Whether the instance currently has saved state on disk
    #[serde(rename = "stateful", skip_serializing_if = "Option::is_none")]
    pub stateful: Option<bool>,
    /// Instance status (see instance_state)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "status_code", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i64>,
    /// The type of instance (container or virtual-machine)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl InstanceFull {
    pub fn new() -> InstanceFull {
        InstanceFull {
            architecture: None,
            backups: None,
            config: None,
            created_at: None,
            description: None,
            devices: None,
            disk_only: None,
            ephemeral: None,
            expanded_config: None,
            expanded_devices: None,
            last_used_at: None,
            location: None,
            name: None,
            profiles: None,
            project: None,
            restore: None,
            snapshots: None,
            state: None,
            stateful: None,
            status: None,
            status_code: None,
            r#type: None,
        }
    }
}

