/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStateMemory {
    /// SWAP usage in bytes
    #[serde(rename = "swap_usage", skip_serializing_if = "Option::is_none")]
    pub swap_usage: Option<i64>,
    /// Peak SWAP usage in bytes
    #[serde(rename = "swap_usage_peak", skip_serializing_if = "Option::is_none")]
    pub swap_usage_peak: Option<i64>,
    /// Total memory size in bytes
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// Memory usage in bytes
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<i64>,
    /// Peak memory usage in bytes
    #[serde(rename = "usage_peak", skip_serializing_if = "Option::is_none")]
    pub usage_peak: Option<i64>,
}

impl InstanceStateMemory {
    pub fn new() -> InstanceStateMemory {
        InstanceStateMemory {
            swap_usage: None,
            swap_usage_peak: None,
            total: None,
            usage: None,
            usage_peak: None,
        }
    }
}

