/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceStateNetworkAddress : InstanceStateNetworkAddress represents a network address as part of the network section of an instance's state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStateNetworkAddress {
    /// IP address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Network family (inet or inet6)
    #[serde(rename = "family", skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    /// Network mask
    #[serde(rename = "netmask", skip_serializing_if = "Option::is_none")]
    pub netmask: Option<String>,
    /// Address scope (local, link or global)
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl InstanceStateNetworkAddress {
    /// InstanceStateNetworkAddress represents a network address as part of the network section of an instance's state.
    pub fn new() -> InstanceStateNetworkAddress {
        InstanceStateNetworkAddress {
            address: None,
            family: None,
            netmask: None,
            scope: None,
        }
    }
}

