/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceLogsGet200Response : Sync response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceLogsGet200Response {
    /// List of endpoints
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Vec<String>>,
    /// Status description
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Status code
    #[serde(rename = "status_code", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
    /// Response type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl InstanceLogsGet200Response {
    /// Sync response
    pub fn new() -> InstanceLogsGet200Response {
        InstanceLogsGet200Response {
            metadata: None,
            status: None,
            status_code: None,
            r#type: None,
        }
    }
}

