/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStateCpu {
    /// CPU time available per second, in nanoseconds
    #[serde(rename = "allocated_time", skip_serializing_if = "Option::is_none")]
    pub allocated_time: Option<i64>,
    /// CPU usage in nanoseconds
    #[serde(rename = "usage", skip_serializing_if = "Option::is_none")]
    pub usage: Option<i64>,
}

impl InstanceStateCpu {
    pub fn new() -> InstanceStateCpu {
        InstanceStateCpu {
            allocated_time: None,
            usage: None,
        }
    }
}

