/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceSnapshot {
    /// Architecture name
    #[serde(rename = "architecture", skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// Instance configuration (see doc/instances.md)
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// Instance creation timestamp
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Instance description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Instance devices (see doc/instances.md)
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<serde_json::Value>,
    /// Whether the instance is ephemeral (deleted on shutdown)
    #[serde(rename = "ephemeral", skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    /// Expanded configuration (all profiles and local config merged)
    #[serde(rename = "expanded_config", skip_serializing_if = "Option::is_none")]
    pub expanded_config: Option<serde_json::Value>,
    /// Expanded devices (all profiles and local devices merged)
    #[serde(rename = "expanded_devices", skip_serializing_if = "Option::is_none")]
    pub expanded_devices: Option<serde_json::Value>,
    /// When the snapshot expires (gets auto-deleted)
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Last start timestamp
    #[serde(rename = "last_used_at", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Snapshot name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// List of profiles applied to the instance
    #[serde(rename = "profiles", skip_serializing_if = "Option::is_none")]
    pub profiles: Option<Vec<String>>,
    /// Size of the snapshot in bytes
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    /// Whether the instance currently has saved state on disk
    #[serde(rename = "stateful", skip_serializing_if = "Option::is_none")]
    pub stateful: Option<bool>,
}

impl InstanceSnapshot {
    pub fn new() -> InstanceSnapshot {
        InstanceSnapshot {
            architecture: None,
            config: None,
            created_at: None,
            description: None,
            devices: None,
            ephemeral: None,
            expanded_config: None,
            expanded_devices: None,
            expires_at: None,
            last_used_at: None,
            name: None,
            profiles: None,
            size: None,
            stateful: None,
        }
    }
}

