/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStateNetwork {
    /// List of IP addresses
    #[serde(rename = "addresses", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<models::InstanceStateNetworkAddress>>,
    #[serde(rename = "counters", skip_serializing_if = "Option::is_none")]
    pub counters: Option<Box<models::InstanceStateNetworkCounters>>,
    /// Name of the interface on the host
    #[serde(rename = "host_name", skip_serializing_if = "Option::is_none")]
    pub host_name: Option<String>,
    /// MAC address
    #[serde(rename = "hwaddr", skip_serializing_if = "Option::is_none")]
    pub hwaddr: Option<String>,
    /// MTU (maximum transmit unit) for the interface
    #[serde(rename = "mtu", skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i64>,
    /// Administrative state of the interface (up/down)
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Type of interface (broadcast, loopback, point-to-point, ...)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl InstanceStateNetwork {
    pub fn new() -> InstanceStateNetwork {
        InstanceStateNetwork {
            addresses: None,
            counters: None,
            host_name: None,
            hwaddr: None,
            mtu: None,
            state: None,
            r#type: None,
        }
    }
}

