/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceStateNetworkCounters : InstanceStateNetworkCounters represents packet counters as part of the network section of an instance's state.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceStateNetworkCounters {
    /// Number of bytes received
    #[serde(rename = "bytes_received", skip_serializing_if = "Option::is_none")]
    pub bytes_received: Option<i64>,
    /// Number of bytes sent
    #[serde(rename = "bytes_sent", skip_serializing_if = "Option::is_none")]
    pub bytes_sent: Option<i64>,
    /// Number of errors received
    #[serde(rename = "errors_received", skip_serializing_if = "Option::is_none")]
    pub errors_received: Option<i64>,
    /// Number of errors sent
    #[serde(rename = "errors_sent", skip_serializing_if = "Option::is_none")]
    pub errors_sent: Option<i64>,
    /// Number of inbound packets dropped
    #[serde(rename = "packets_dropped_inbound", skip_serializing_if = "Option::is_none")]
    pub packets_dropped_inbound: Option<i64>,
    /// Number of outbound packets dropped
    #[serde(rename = "packets_dropped_outbound", skip_serializing_if = "Option::is_none")]
    pub packets_dropped_outbound: Option<i64>,
    /// Number of packets received
    #[serde(rename = "packets_received", skip_serializing_if = "Option::is_none")]
    pub packets_received: Option<i64>,
    /// Number of packets sent
    #[serde(rename = "packets_sent", skip_serializing_if = "Option::is_none")]
    pub packets_sent: Option<i64>,
}

impl InstanceStateNetworkCounters {
    /// InstanceStateNetworkCounters represents packet counters as part of the network section of an instance's state.
    pub fn new() -> InstanceStateNetworkCounters {
        InstanceStateNetworkCounters {
            bytes_received: None,
            bytes_sent: None,
            errors_received: None,
            errors_sent: None,
            packets_dropped_inbound: None,
            packets_dropped_outbound: None,
            packets_received: None,
            packets_sent: None,
        }
    }
}

