/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceState {
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<Box<models::InstanceStateCpu>>,
    /// Disk usage key/value pairs
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<std::collections::HashMap<String, models::InstanceStateDisk>>,
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<Box<models::InstanceStateMemory>>,
    /// Network usage key/value pairs
    #[serde(rename = "network", skip_serializing_if = "Option::is_none")]
    pub network: Option<std::collections::HashMap<String, models::InstanceStateNetwork>>,
    #[serde(rename = "os_info", skip_serializing_if = "Option::is_none")]
    pub os_info: Option<Box<models::InstanceStateOsInfo>>,
    /// PID of the runtime
    #[serde(rename = "pid", skip_serializing_if = "Option::is_none")]
    pub pid: Option<i64>,
    /// Number of processes in the instance
    #[serde(rename = "processes", skip_serializing_if = "Option::is_none")]
    pub processes: Option<i64>,
    /// The time that the instance started at  API extension: instance_state_started_at.
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Current status (Running, Stopped, Frozen or Error)
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "status_code", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i64>,
}

impl InstanceState {
    pub fn new() -> InstanceState {
        InstanceState {
            cpu: None,
            disk: None,
            memory: None,
            network: None,
            os_info: None,
            pid: None,
            processes: None,
            started_at: None,
            status: None,
            status_code: None,
        }
    }
}

