/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstancePostTarget {
    /// The certificate of the migration target
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<String>,
    /// The operation URL on the remote target
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// Migration websockets credentials
    #[serde(rename = "secrets", skip_serializing_if = "Option::is_none")]
    pub secrets: Option<std::collections::HashMap<String, String>>,
}

impl InstancePostTarget {
    pub fn new() -> InstancePostTarget {
        InstancePostTarget {
            certificate: None,
            operation: None,
            secrets: None,
        }
    }
}

