/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstanceBackup {
    /// When the backup was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// When the backup expires (gets auto-deleted)
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Whether to ignore snapshots
    #[serde(rename = "instance_only", skip_serializing_if = "Option::is_none")]
    pub instance_only: Option<bool>,
    /// Backup name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether to use a pool-optimized binary format (instead of plain tarball)
    #[serde(rename = "optimized_storage", skip_serializing_if = "Option::is_none")]
    pub optimized_storage: Option<bool>,
}

impl InstanceBackup {
    pub fn new() -> InstanceBackup {
        InstanceBackup {
            created_at: None,
            expires_at: None,
            instance_only: None,
            name: None,
            optimized_storage: None,
        }
    }
}

