/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerStorageDriverInfo : ServerStorageDriverInfo represents the read-only info about a storage driver
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerStorageDriverInfo {
    /// Name of the driver
    #[serde(rename = "Name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Whether the driver has remote volumes
    #[serde(rename = "Remote", skip_serializing_if = "Option::is_none")]
    pub remote: Option<bool>,
    /// Version of the driver
    #[serde(rename = "Version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ServerStorageDriverInfo {
    /// ServerStorageDriverInfo represents the read-only info about a storage driver
    pub fn new() -> ServerStorageDriverInfo {
        ServerStorageDriverInfo {
            name: None,
            remote: None,
            version: None,
        }
    }
}

