/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerUntrusted : ServerUntrusted represents a server configuration for an untrusted client
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerUntrusted {
    /// List of supported API extensions
    #[serde(rename = "api_extensions", skip_serializing_if = "Option::is_none")]
    pub api_extensions: Option<Vec<String>>,
    /// Support status of the current API (one of \"devel\", \"stable\" or \"deprecated\")
    #[serde(rename = "api_status", skip_serializing_if = "Option::is_none")]
    pub api_status: Option<String>,
    /// API version number
    #[serde(rename = "api_version", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// Whether the client is trusted (one of \"trusted\" or \"untrusted\")
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<String>,
    /// List of supported authentication methods
    #[serde(rename = "auth_methods", skip_serializing_if = "Option::is_none")]
    pub auth_methods: Option<Vec<String>>,
    /// Server configuration map (refer to doc/server.md)
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
    /// Whether the server is public-only (only public endpoints are implemented)
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
}

impl ServerUntrusted {
    /// ServerUntrusted represents a server configuration for an untrusted client
    pub fn new() -> ServerUntrusted {
        ServerUntrusted {
            api_extensions: None,
            api_status: None,
            api_version: None,
            auth: None,
            auth_methods: None,
            config: None,
            public: None,
        }
    }
}

