/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServerPut : ServerPut represents the modifiable fields of a server configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerPut {
    /// Server configuration map (refer to doc/server.md)
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
}

impl ServerPut {
    /// ServerPut represents the modifiable fields of a server configuration
    pub fn new() -> ServerPut {
        ServerPut {
            config: None,
        }
    }
}

