/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StorageVolumeBitmapsPost : StorageVolumeBitmapsPost represents the fields available for a new volume bitmap
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageVolumeBitmapsPost {
    /// The bitmap is created in the disabled state
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    /// Granularity of the dirty bitmap in bytes
    #[serde(rename = "granularity", skip_serializing_if = "Option::is_none")]
    pub granularity: Option<i64>,
    /// Bitmap name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// true if the bitmap was stored on disk, is scheduled to be stored on disk, or both
    #[serde(rename = "persistent", skip_serializing_if = "Option::is_none")]
    pub persistent: Option<bool>,
}

impl StorageVolumeBitmapsPost {
    /// StorageVolumeBitmapsPost represents the fields available for a new volume bitmap
    pub fn new() -> StorageVolumeBitmapsPost {
        StorageVolumeBitmapsPost {
            disabled: None,
            granularity: None,
            name: None,
            persistent: None,
        }
    }
}

