/*
 * Incus external REST API
 *
 * This is the REST API used by all Incus clients. Internal endpoints aren't included in this documentation.  The Incus API is available over both a local unix+http and remote https API. Authentication for local users relies on group membership and access to the unix socket. For remote users, the default authentication method is TLS client certificates.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lxc-devel@lists.linuxcontainers.org
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`image_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImageDeleteError {
    Status400(models::InstancesPut400Response),
    Status403(models::InstancesGet403Response),
    Status500(models::InstancesGet500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`image_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImageGetError {
    Status403(models::InstancesGet403Response),
    Status500(models::InstancesGet500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`image_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImagePatchError {
    Status400(models::InstancesPut400Response),
    Status403(models::InstancesGet403Response),
    Status412(models::InstanceMetadataPut412Response),
    Status500(models::InstancesGet500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`image_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImagePutError {
    Status400(models::InstancesPut400Response),
    Status403(models::InstancesGet403Response),
    Status412(models::InstanceMetadataPut412Response),
    Status500(models::InstancesGet500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`images_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ImagesGetError {
    Status403(models::InstancesGet403Response),
    Status500(models::InstancesGet500Response),
    UnknownValue(serde_json::Value),
}


/// Removes the image from the image store.
pub async fn image_delete(configuration: &configuration::Configuration, fingerprint: &str, project: Option<&str>) -> Result<models::InstancesPut202Response, Error<ImageDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fingerprint = fingerprint;
    let p_query_project = project;

    let uri_str = format!("{}/1.0/images/{fingerprint}", configuration.base_path, fingerprint=crate::apis::urlencode(p_path_fingerprint));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_project {
        req_builder = req_builder.query(&[("project", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InstancesPut202Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InstancesPut202Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ImageDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Gets a specific image.
pub async fn image_get(configuration: &configuration::Configuration, fingerprint: &str, project: Option<&str>) -> Result<models::ImageGet200Response, Error<ImageGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fingerprint = fingerprint;
    let p_query_project = project;

    let uri_str = format!("{}/1.0/images/{fingerprint}", configuration.base_path, fingerprint=crate::apis::urlencode(p_path_fingerprint));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_project {
        req_builder = req_builder.query(&[("project", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ImageGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ImageGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ImageGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a subset of the image definition.
pub async fn image_patch(configuration: &configuration::Configuration, fingerprint: &str, image: models::ImagePut, project: Option<&str>) -> Result<models::InstancePatch200Response, Error<ImagePatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fingerprint = fingerprint;
    let p_body_image = image;
    let p_query_project = project;

    let uri_str = format!("{}/1.0/images/{fingerprint}", configuration.base_path, fingerprint=crate::apis::urlencode(p_path_fingerprint));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref param_value) = p_query_project {
        req_builder = req_builder.query(&[("project", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_image);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InstancePatch200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InstancePatch200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ImagePatchError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates the entire image definition.
pub async fn image_put(configuration: &configuration::Configuration, fingerprint: &str, image: models::ImagePut, project: Option<&str>) -> Result<models::InstancePatch200Response, Error<ImagePutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_fingerprint = fingerprint;
    let p_body_image = image;
    let p_query_project = project;

    let uri_str = format!("{}/1.0/images/{fingerprint}", configuration.base_path, fingerprint=crate::apis::urlencode(p_path_fingerprint));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_project {
        req_builder = req_builder.query(&[("project", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_image);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::InstancePatch200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::InstancePatch200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ImagePutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of images (URLs).
pub async fn images_get(configuration: &configuration::Configuration, project: Option<&str>, filter: Option<&str>, all_projects: Option<bool>) -> Result<models::ImagesGet200Response, Error<ImagesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_project = project;
    let p_query_filter = filter;
    let p_query_all_projects = all_projects;

    let uri_str = format!("{}/1.0/images", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_project {
        req_builder = req_builder.query(&[("project", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_filter {
        req_builder = req_builder.query(&[("filter", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_all_projects {
        req_builder = req_builder.query(&[("all-projects", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ImagesGet200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ImagesGet200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ImagesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

